# Get all book
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json



###

# Create a Book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title":"Richa dad and poor dad"
}


###

#Update a Book

PUT http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title":"Mind is powerful weapone"
}

###
#Delete a book

DELETE  http://localhost:3001/books HTTP/1.1
Content-Type: application/json

